### PR TITLE
Page buttons mege with master

### PR DESCRIPTION
**Pull request by rcmorrill**

### CODE REVIEW

**Comment by liapetronio** [comment]
The git-pgs still isn't working. Do you know how to fix it?

On Sunday, February 21, 2016, rcmorrill <notifications@github.com> wrote:

> Merged #9 <https://github.com/liapetronio/Co_op_NEU/pull/9>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liapetronio/Co_op_NEU/pull/9#event-558405739>.
>


-- 
Lia Petronio
MFA Candidate, Information Design and Visualization
Northeastern University, College of Arts, Media, and Design
lia.marie.petronio@gmail.com | 201-264-0597

**Comment by liapetronio** [comment]
Actually I think I just fixed it/it's working now

On Sunday, February 21, 2016, lia petronio <lia.marie.petronio@gmail.com>
wrote:

> The git-pgs still isn't working. Do you know how to fix it?
>
> On Sunday, February 21, 2016, rcmorrill <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Merged #9 <https://github.com/liapetronio/Co_op_NEU/pull/9>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/liapetronio/Co_op_NEU/pull/9#event-558405739>.
>>
>
>
> --
> Lia Petronio
> MFA Candidate, Information Design and Visualization
> Northeastern University, College of Arts, Media, and Design
> lia.marie.petronio@gmail.com
> <javascript:_e(%7B%7D,'cvml','lia.marie.petronio@gmail.com');> |
> 201-264-0597
>
>

-- 
Lia Petronio
MFA Candidate, Information Design and Visualization
Northeastern University, College of Arts, Media, and Design
lia.marie.petronio@gmail.com | 201-264-0597

**Comment by rcmorrill** [comment]
Hey -- I think we're both doing stuff.

I created a new gh-pages branch after merging "page-buttons" into master.

**Comment by liapetronio** [comment]
Ok got it. I just sent you and Renata email with new link that works. Try
link to make sure

On Sunday, February 21, 2016, rcmorrill <notifications@github.com> wrote:

> Hey -- I think we're both doing stuff.
>
> I created a new gh-pages branch after merging "page-buttons" into master.
>
> On Sun, Feb 21, 2016 at 10:01 AM, liapetronio <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Actually I think I just fixed it/it's working now
> >
> > On Sunday, February 21, 2016, lia petronio <lia.marie.petronio@gmail.com
> <javascript:_e(%7B%7D,'cvml','lia.marie.petronio@gmail.com');>>
> > wrote:
> >
> > > The git-pgs still isn't working. Do you know how to fix it?
> > >
> > > On Sunday, February 21, 2016, rcmorrill <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > >> Merged #9 <https://github.com/liapetronio/Co_op_NEU/pull/9>.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/liapetronio/Co_op_NEU/pull/9#event-558405739>.
> > >>
> > >
> > >
> > > --
> > > Lia Petronio
> > > MFA Candidate, Information Design and Visualization
> > > Northeastern University, College of Arts, Media, and Design
> > > lia.marie.petronio@gmail.com
> <javascript:_e(%7B%7D,'cvml','lia.marie.petronio@gmail.com');>
> > > <javascript:_e(%7B%7D,'cvml','lia.marie.petronio@gmail.com
> <javascript:_e(%7B%7D,'cvml','lia.marie.petronio@gmail.com');>');> |
> > > 201-264-0597
> >
> > >
> > >
> >
> > --
> > Lia Petronio
> > MFA Candidate, Information Design and Visualization
> > Northeastern University, College of Arts, Media, and Design
> > lia.marie.petronio@gmail.com
> <javascript:_e(%7B%7D,'cvml','lia.marie.petronio@gmail.com');> |
> 201-264-0597
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/liapetronio/Co_op_NEU/pull/9#issuecomment-186835550
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liapetronio/Co_op_NEU/pull/9#issuecomment-186835752>.
>


-- 
Lia Petronio
MFA Candidate, Information Design and Visualization
Northeastern University, College of Arts, Media, and Design
lia.marie.petronio@gmail.com | 201-264-0597

**Pull request merged**
